name: CI with SOAPUI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Start Service A
        run: nohup node src/service-a/app.js &

      - name: Start Service B
        run: nohup node src/service-b/app.js &

      - name: Download and install SOAPUI
        run: |
          wget https://dl.eviware.com/soapuios/5.9.1/SoapUI-x64-5.9.1.sh
          chmod +x SoapUI-x64-5.9.1.sh
          ./SoapUI-x64-5.9.1.sh -q -dir /opt/SoapUI
        shell: bash

      - name: Run tests
        run: npm test
        working-directory: ./src

      - name: Run SOAPUI tests
        run: /opt/SoapUI/bin/testrunner.sh -r src/tests/soapui-project.xml
        env:
          SOAPUI_HOME: /opt/SoapUI